/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehicleSecurityRouteImport } from './routes/vehicle-security'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as LightingRouteImport } from './routes/lighting'
import { Route as HomeTheaterRouteImport } from './routes/home-theater'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarAudioRouteImport } from './routes/car-audio'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'

const VehicleSecurityRoute = VehicleSecurityRouteImport.update({
  id: '/vehicle-security',
  path: '/vehicle-security',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const LightingRoute = LightingRouteImport.update({
  id: '/lighting',
  path: '/lighting',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeTheaterRoute = HomeTheaterRouteImport.update({
  id: '/home-theater',
  path: '/home-theater',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarAudioRoute = CarAudioRouteImport.update({
  id: '/car-audio',
  path: '/car-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/car-audio': typeof CarAudioRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/home-theater': typeof HomeTheaterRoute
  '/lighting': typeof LightingRoute
  '/quote': typeof QuoteRoute
  '/vehicle-security': typeof VehicleSecurityRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/car-audio': typeof CarAudioRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/home-theater': typeof HomeTheaterRoute
  '/lighting': typeof LightingRoute
  '/quote': typeof QuoteRoute
  '/vehicle-security': typeof VehicleSecurityRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/car-audio': typeof CarAudioRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/home-theater': typeof HomeTheaterRoute
  '/lighting': typeof LightingRoute
  '/quote': typeof QuoteRoute
  '/vehicle-security': typeof VehicleSecurityRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/car-audio'
    | '/contact'
    | '/gallery'
    | '/home-theater'
    | '/lighting'
    | '/quote'
    | '/vehicle-security'
    | '/guides/$slug'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/car-audio'
    | '/contact'
    | '/gallery'
    | '/home-theater'
    | '/lighting'
    | '/quote'
    | '/vehicle-security'
    | '/guides/$slug'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/car-audio'
    | '/contact'
    | '/gallery'
    | '/home-theater'
    | '/lighting'
    | '/quote'
    | '/vehicle-security'
    | '/guides/$slug'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CarAudioRoute: typeof CarAudioRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  HomeTheaterRoute: typeof HomeTheaterRoute
  LightingRoute: typeof LightingRoute
  QuoteRoute: typeof QuoteRoute
  VehicleSecurityRoute: typeof VehicleSecurityRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicle-security': {
      id: '/vehicle-security'
      path: '/vehicle-security'
      fullPath: '/vehicle-security'
      preLoaderRoute: typeof VehicleSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lighting': {
      id: '/lighting'
      path: '/lighting'
      fullPath: '/lighting'
      preLoaderRoute: typeof LightingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-theater': {
      id: '/home-theater'
      path: '/home-theater'
      fullPath: '/home-theater'
      preLoaderRoute: typeof HomeTheaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-audio': {
      id: '/car-audio'
      path: '/car-audio'
      fullPath: '/car-audio'
      preLoaderRoute: typeof CarAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CarAudioRoute: CarAudioRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  HomeTheaterRoute: HomeTheaterRoute,
  LightingRoute: LightingRoute,
  QuoteRoute: QuoteRoute,
  VehicleSecurityRoute: VehicleSecurityRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
